[build]
  # Build command that Netlify should use to build your site
  command = "cd client && npm i && npm run build"
  # The directory where the built files are located after running the build command
  publish = "client/dist"

# Directory where Netlify functions are stored
[functions]
  directory = "backend"